### PR TITLE
fixed typespecs

### PR DESCRIPTION
**Pull request by albertored**

### CODE REVIEW

**Comment by vantalter** [comment]
@danhper is this something you can take a look on? It should really help to fix dialyzer issues especially `no local return` that I am also currently facing with.

**Comment by danhper** [comment]
Sorry for the delay and thank you. I just pushed a new version to hex.

**Comment by albertored** [comment]
@danhper it seems that the new pushed version on hex (0.4.6) does not contain this fix

**Comment by danhper** [comment]
I must have been very tired :sweat: 
This should now be fixed

**Pull request merged**
